name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        package:
          - core
          - catalog-management
          - reservation-management
          - billing-management
          - notification-management
    steps:
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Auth Dev Hub
        run: echo "${{ secrets.DEV_HUB_SFDX_AUTH_URL }}" | sf org login sfdx-url --alias dev-hub --set-default-dev-hub --sfdx-url-stdin

      - name: Create Package Version
        id: create
        run: |
          PACKAGE_CREATE_JSON=$(sf package version create --package "${{ matrix.package }}" --installation-key-bypass --code-coverage --wait 30 --json || true)

          PACKAGE_CREATE_VERSION=$(echo "$PACKAGE_CREATE_JSON" | jq -r '.result.SubscriberPackageVersionId')

          if [ -z "$PACKAGE_CREATE_VERSION" ] || [ "$PACKAGE_CREATE_VERSION" = "null" ]; then
            echo "Error: Failed to create package version."
            echo "$PACKAGE_CREATE_JSON" | jq .
            exit 1
          fi

          echo "version=$PACKAGE_CREATE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Auth QA
        run: echo "${{ secrets.QA_SFDX_AUTH_URL }}" | sf org login sfdx-url --alias qa --sfdx-url-stdin

      - name: Install in QA
        run: sf package install --package "${{ steps.create.outputs.version }}" --target-org qa --wait 20 --publish-wait 10
        
      - name: Promote Package Version
        run: sf package version promote --package "${{ steps.create.outputs.version }}" --no-prompt
        
      - name: Auth Production
        run: echo "${{ secrets.PRODUCTION_SFDX_AUTH_URL }}" | sf org login sfdx-url --alias production --sfdx-url-stdin

      - name: Install in Production
        run: sf package install --package "${{ steps.create.outputs.version }}" --target-org production --wait 20 --publish-wait 10
